---
- hosts: all
  become: true
  tasks:

    - name: enable https apt functionality
      apt: name=apt-transport-https update_cache=yes

    - name: install pycurl package in order to use the apt_repository module
      apt: pkg=python-pycurl state=present

    - name: add nodesource key to apt
      apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

    - name: add nodesource repo to apt
      apt_repository:
        repo: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - deb https://deb.nodesource.com/node_10.x {{ ansible_lsb.codename }} main
        - deb-src https://deb.nodesource.com/node_10.x {{ ansible_lsb.codename }} main

    - name: Add an Apt signing key for postgrsql 9.6
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Add Postgresql 9.6 repo to apt
      apt_repository:
        repo: deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main
        state: present

    - name: install packages from apt
      apt: name={{ item }}
      with_items:
        - libjpeg-dev
        - libfontconfig
        - libpq-dev
        - postgresql-9.6
        - postgresql-contrib
        - postgresql-server-dev-all
        - python3-dev
        - python3-psycopg2
        - python3-pip
        - redis-server
        - nodejs
        - git


- hosts: all
  become: true
  become_user: postgres
  tasks:
    - name: create database vagrant
      postgresql_db: name=vagrant

    - name: create postgres user vagrant with access to vagrant
      postgresql_user: db=vagrant name=vagrant encrypted=yes role_attr_flags=CREATEDB 

    - name: create database ubuntu
      postgresql_db: name=ubuntu

    - name: create postgres user ubuntu with access to vagrant
      postgresql_user: db=ubuntu name=ubuntu password=ubuntu encrypted=yes role_attr_flags=CREATEDB
